<?xml version="1.0" encoding="UTF-8"?>
<robot generator="Robot 5.0.1 (Python 3.9.13 on win32)" generated="20230919 10:58:03.884" rpa="true" schemaversion="3">
<suite id="s1" name="Tasks" source="c:\Users\saira\OneDrive\Desktop\DemoRobot\tasks.robot">
<test id="s1-t1" name="Rename" line="65">
<kw name="Move File" library="OperatingSystem">
<arg>${OUTPUT_DIR}\\viewAttachment.pdf</arg>
<arg>${OUTPUT_DIR}\\Invoice.pdf</arg>
<doc>Moves the source file into the destination.</doc>
<msg timestamp="20230919 10:58:08.221" level="FAIL">Source file 'C:\Users\saira\OneDrive\Desktop\DemoRobot\viewAttachment.pdf' does not exist.</msg>
<status status="FAIL" starttime="20230919 10:58:08.221" endtime="20230919 10:58:08.221"/>
</kw>
<kw name="Log" library="BuiltIn">
<arg>Task Completed</arg>
<doc>Logs the given message with the given level.</doc>
<status status="NOT RUN" starttime="20230919 10:58:08.245" endtime="20230919 10:58:08.245"/>
</kw>
<status status="FAIL" starttime="20230919 10:58:08.221" endtime="20230919 10:58:08.245">Source file 'C:\Users\saira\OneDrive\Desktop\DemoRobot\viewAttachment.pdf' does not exist.</status>
</test>
<doc>Template robot main suite.</doc>
<status status="FAIL" starttime="20230919 10:58:03.894" endtime="20230919 10:58:08.265"/>
</suite>
<statistics>
<total>
<stat pass="0" fail="1" skip="0">All Tasks</stat>
</total>
<tag>
</tag>
<suite>
<stat pass="0" fail="1" skip="0" id="s1" name="Tasks">Tasks</stat>
</suite>
</statistics>
<errors>
</errors>
</robot>
